name: github to pypi pipline

on:
  pull_request: 
    branches: 
      - master

jobs:
  pypi-pyblish: 
    name: publish to pypi
    runs-on: ubuntu-latest

    steps:
    - name: checking code 
      uses: actions/checkout@v3

    - name: setting up python
      uses: actions/setup-python@v3
      with:
        python-version: 3.x

    - name: install deps
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: |
        python -m build

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        repository-url: https://pypi.org/legacy/ 

